name: Keep portage-stable packages updated
on:
  schedule:
    - cron:  '0 7 * * 1'
  workflow_dispatch:

jobs:
  keep-packages-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Check out scripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./scripts
      - name: Check out Gentoo
        uses: actions/checkout@v4
        with:
          repository: gentoo/gentoo
          path: gentoo
          # Gentoo is quite a large repo, so limit ourselves to last
          # quarter milion of commits. It is about two years worth of changes.
          # Is is needed by the sync script to find out the hash of the last commit
          # that made the changes to the package.
          fetch-depth: 250000
          ref: master
      - name: Update listed packages
        id: update-listed-packages
        run: ./scripts/.github/workflows/sync_packages.sh ./scripts main ./gentoo
      - name: Create pull request for main branch
        uses: peter-evans/create-pull-request@v6
        if: steps.update-listed-packages.outputs.UPDATED == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: scripts
          branch: ${{steps.update-listed-packages.outputs.BRANCH }}
          base: main
          title: Weekly portage-stable package updates ${{steps.update-listed-packages.outputs.TODAYDATE }}
          body-path: ${{steps.update-listed-packages.outputs.BODY_PATH }}
          labels: main
          draft: true
